// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBD5IsxH353WwV419VV8NYH29X9raMjfk',
    appId: '1:881537062488:web:b2d932bf7455c29b551c2d',
    messagingSenderId: '881537062488',
    projectId: 'unival-quiz-apps',
    authDomain: 'unival-quiz-apps.firebaseapp.com',
    storageBucket: 'unival-quiz-apps.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCruQdVIqfaCJmHI0Hwd1L9ggbMtwXppag',
    appId: '1:881537062488:android:3d9cf866e8d16497551c2d',
    messagingSenderId: '881537062488',
    projectId: 'unival-quiz-apps',
    storageBucket: 'unival-quiz-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHtYO09XyoBP22JerDqoCXqvKRfknjj2c',
    appId: '1:881537062488:ios:8c632826cce4dc59551c2d',
    messagingSenderId: '881537062488',
    projectId: 'unival-quiz-apps',
    storageBucket: 'unival-quiz-apps.firebasestorage.app',
    iosBundleId: 'com.example.quizApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHtYO09XyoBP22JerDqoCXqvKRfknjj2c',
    appId: '1:881537062488:ios:8c632826cce4dc59551c2d',
    messagingSenderId: '881537062488',
    projectId: 'unival-quiz-apps',
    storageBucket: 'unival-quiz-apps.firebasestorage.app',
    iosBundleId: 'com.example.quizApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBD5IsxH353WwV419VV8NYH29X9raMjfk',
    appId: '1:881537062488:web:a8d97a672ae3537d551c2d',
    messagingSenderId: '881537062488',
    projectId: 'unival-quiz-apps',
    authDomain: 'unival-quiz-apps.firebaseapp.com',
    storageBucket: 'unival-quiz-apps.firebasestorage.app',
  );
}
